### ISSUE TITLE
ACF Datetime fields return as null

### ISSUE THREAD

**Issue by sirichards** [wp-graphql/wp-graphql-acf#108]
Hey,

I have an issue where ACF date time picker fields are returned as null in GraphQL.

![2](https://user-images.githubusercontent.com/21104091/74850199-96662180-5331-11ea-9a51-fc5544dd4320.jpg)

Data comes through in the rest API.

![3](https://user-images.githubusercontent.com/21104091/74850200-96662180-5331-11ea-9e7f-14d6f6ca0697.jpg)

Could be related to #18

**Comment by Hansanghyeon** [comment]
![](https://cdn4log.s3.ap-northeast-2.amazonaws.com/images/img1.png)
I get this error in the value for a datetime field and return null.

**Comment by jasonbahl** [comment]
@Hansanghyeon what error do you get? It looks like the image you tried to add doesn't exist.

**Comment by jasonbahl** [comment]
@sirichards I'm unable to replicate this behavior. 

I created an ACF Field Group with a Date Picker, DateTime Picker, and Time Picker, and saved a post with values. 

![Screen Shot 2020-03-31 at 5 04 26 PM](https://user-images.githubusercontent.com/1260765/78083159-f2c95180-7371-11ea-8d13-6e0c3743bd9a.png)

I then query the Post in GraphQL, and get the values returned:

![Screen Shot 2020-03-31 at 5 04 09 PM](https://user-images.githubusercontent.com/1260765/78083188-02489a80-7372-11ea-990c-f94009deea03.png)

Can you provide more information so I can replicate? 

- What version of WordPress
- What version of WPGraphQL?
- What version of ACF?
- What version of WPGraphQL for ACF?
- Can you provide a JSON export of the ACF field group(s) that are mis-behaving?

**Comment by Hansanghyeon** [comment]
Tested again. I have confirmed that the date field works without problems. Thank you. 🙏

- wp-graphql 0.8.0 update
- acf-pro 5.7.7
- wp-graphql-acf 0.3.1

**Comment by jasonbahl** [comment]
Thanks for the follow-up @Hansanghyeon!

**Comment by benleeth** [comment]
I, too, am having this issue but only in the Options.

Localhost GraphiQL
![alt text](https://designontap.com/app/uploads/2020/04/3.png "Localhost GraphiQl")

GUI GraphiQL
![alt text](https://designontap.com/app/uploads/2020/04/4.png "GUI GraphiQl")

Options page
![alt text](https://designontap.com/app/uploads/2020/04/5.png "Admin")

DB
![alt text](https://designontap.com/app/uploads/2020/04/6.png "Database")

WordPress 5.3.2
WP GraphQL 0.8.0
WPGraphQL for Advanced Custom Fields 0.3.1

**Comment by jasonbahl** [comment]
@benleeth looking into this 👀

**Comment by benleeth** [comment]
@jasonbahl, thanks!

**Comment by jasonbahl** [comment]
@benleeth have a PR here (https://github.com/wp-graphql/wp-graphql-acf/pull/125) that I believe addresses this. 

I have a test Post with a datetime field and a flex field with a datetime within it: 

![Screen Shot 2020-04-16 at 8 59 18 PM](https://user-images.githubusercontent.com/1260765/79527561-2cae7f00-8025-11ea-8d64-ab533c5dbba6.png)


I also setup an options page similar to yours: 

![Screen Shot 2020-04-16 at 8 52 55 PM](https://user-images.githubusercontent.com/1260765/79527575-346e2380-8025-11ea-8b6d-71fe0415fb68.png)

Below are the queries I tried: 

**Before**

![Screen Shot 2020-04-16 at 8 57 57 PM](https://user-images.githubusercontent.com/1260765/79527599-418b1280-8025-11ea-9905-ec4e113749e9.png)


**After**

![Screen Shot 2020-04-16 at 8 56 58 PM](https://user-images.githubusercontent.com/1260765/79527637-5798d300-8025-11ea-9974-d91c0194620d.png)

**Comment by jasonbahl** [comment]
@benleeth this fix has been released in v0.3.2

**Comment by adeluleye** [comment]
@jasonbahl Thanks for this release of v0.3.2.
I was initially having issue querying a date picker field with v0.3.1 as I always get an Internal Server Error. When I updated to v0.3.2, the error stopped but I still get a wrong date returned.

Here are my screenshots:
<img width="446" alt="Screenshot 2020-04-19 at 10 34 14 AM" src="https://user-images.githubusercontent.com/8542308/79684530-1a516280-822a-11ea-899f-0cc13eb287da.png">

<img width="650" alt="Screenshot 2020-04-19 at 10 39 15 AM" src="https://user-images.githubusercontent.com/8542308/79684531-1faead00-822a-11ea-9f24-4b7d5769c90b.png">

Any idea why i keep getting same date of `22/08/1970`?

I'm using WPGraphQL 0.4.1, I have also tried 0.8.3 but same behavior
WPGraphQL ACF 0.3.2
ACF Pro 5.8.3
WordPress version: using 4.8.2 before when I got that behavior, upgraded to 5.4 and still same issue.

**Comment by jasonbahl** [comment]
gah! 

I'll see what I can find out.

**Comment by stephanedemotte** [comment]
@jasonbahl any update on this ?

**Comment by jasonbahl** [comment]
@stephanedemotte try v0.3.3 

https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.3.3

**Comment by JorgeSivil** [comment]
I'm sorry to revive an old thread but I wanted to contribute my bug since this is one of the first google results

in the ACF php definition we had this

'return_format' => 'YYYY-MM-DD'

which was causing the field to always return null

I changed it to 'return_format' => 'Y-m-d', and it fixed the issue
