### ISSUE TITLE
Acf fields return null with repeater/group

### ISSUE THREAD

**Issue by lnikell** [wp-graphql/wp-graphql-acf#170]
I have the following problem, that I think relates to this plugin:
- I have a custom post type
- There are 2 different ACF groups with repeater assigned to 2 different posts within this post type
- This repeater field named "items"
- First ACF groups has items with fields "title", "date", second one has items with fields "title", "description", "url"
- When you query over WP GraphiQL for the second post description and url will be always "null", until you change the name of repeated to a different one. From "items" to "items_second" for example

ACF version - 5.8.12
WP GraphQL - 0.12.3
WPGraphQL for Advanced Custom Fields - 0.3.5 (Tested on 0.4 too)
Custom Post Type UI - 1.8.0

**Comment by alexfromesper** [comment]
Yeah this not only occurs with the "Repeater" field type but also the "Group" and "Gallery" field types.
Any types that have children seem to be effected.

It gets quite annoying when you have to rename each field that has child nodes.
This murders scalability when trying to implement scalable structures (I.E. repeating rows, columns, etc)

**Comment by rburgst** [comment]
Note that this was working fine in

* WP GraphQL: 0.9.1
* WP GraphQL ACF: 0.3.3
* ACF : 5.8.7 (note that I can replicate the problem with this version and the latest verison of WP GraphQL+ACF, so IMHO the ACF version is not relevant).

**Comment by rburgst** [comment]
Note that this was working fine in

* WP GraphQL: 0.9.1
* WP GraphQL ACF: 0.3.3
* ACF : 5.8.7 (note that I can replicate the problem with this version and the latest verison of WP GraphQL+ACF, so IMHO the ACF version is not relevant).

**Comment by rburgst** [comment]
Correction, I am no longer to replicate the issue. My problem was that my DB was broken and the ACFs did indeed have no content any longer. After restoring the DB I can see values of repeater fields even if multiple sub-fields have the same name.

**Comment by rburgst** [comment]
ok, now I can replicate it again with wp-graphql-acf 0.3.5.

I have 2 custom fields which have the same named repeater, lets say they are called `acf1` and `acf2`. 

Both of them have a repeater field called  `link` that have (among others) a text fields with the name `buttonText`.

On the page itself only `acf2` is configured.

If I only query `acf2` then everything works as expected:

```graphql
query {
  page(id: "8796053", idType: DATABASE_ID) {
    id
    slug
    title
    acf2 {      
      links {
        buttonText
      }
    }
  }
}
```
=> 
```json
  "data": {
    "page": {
      "id": "cG9zdDo4Nzk2MDUz",
      "slug": "my-page",
      "title": "my page",
      "acf2": {
        "links": [
          {
            "buttonText": "my button text"
          },
          ...
```

however if I query both fields (even though on the page `acf1` is not configured) the data shows up for `acf1`, rather than `acf2`.

```graphql
query {
  page(id: "8796053", idType: DATABASE_ID) {
    id
    slug
    title
    acf1 {
      links {
        buttonText
      }
    }
    acf2 {      
      links {
        buttonText
      }
    }
  }
}
```

=> 
```json
  "data": {
    "page": {
      "id": "cG9zdDo4Nzk2MDUz",
      "slug": "my-page",
      "title": "my page",
      "acf1": {
        "links": [
          {
            "buttonText": "my button text"
          },
          ...
      "acf2": {
        "links": [
          {
            "buttonText": null
          },
          {
            "buttonText": null
          },
```

**Comment by rburgst** [comment]
I think I tracked down the problem to be an ACF bug, when you query `acf1\links` via 
```
			$field_value = get_field( $key, $id, $format );
```
and the `$key` is the wrong (ie. `acf1`) field, the actual lookup in the DB will be performed using the `field_name` i.e. `links` rather than the field id, then ACF will cache the value in its internal cache using the wrong field ids (since it looked up the values not via id but the field name which is not unique)

So this is most likely an ACF caching bug that does not have a lot to do with wp-graphql-acf (or rather where wp-graphql-acf cannot really work around this problem).

**Comment by rburgst** [comment]
I managed to work around the caching problem by patching `acf-value-functions.php` in principle you need to search the whole file for `$post_id:$field_name` and instead use the `$post_id:$field_name:$field_key`. Need to check the latest ACF pro version whether this has been fixed in more recent versions.

**Comment by rburgst** [comment]
created a patch for ACF, lets see if they take it

**Comment by lnikell** [comment]
@rburgst I guess it's a bit different issue you're talking about. In my case, if there are multiple objects in DB with the same ACF groups/repeaters names there is some overlapping problem when it just does not show fields.

So for the time being the workaround just name those groups differently.

**Comment by rburgst** [comment]
I believe your problem is exactly the same as mine. As stated above, the problem is wrong caching, the cache is stored with the wrong field id. In my case I also get all `null` values from graphql.

**Comment by rburgst** [comment]
you can try out my patch (https://github.com/AdvancedCustomFields/acf/pull/403) and see if it helps.

**Comment by jasonbahl** [comment]
@rburgst @lnikell we've been discussing changing how field groups are mapped to the GraphQL Schema, and I hope the changes to that will resolve this. 

Right now this plugin tries to interpret the ACF location rules and attempt to map to the WPGraphQL Schema, but there are a lot of things that don't map really well, and issues like this come up. 

I believe that if we can better validate what field groups are assigned to which Types in the GraphQL Schema, this should resolve this issue. 

I've added this issue to the "ACF Schema Location Rules" milestone so we can keep it top of mind as we work on that problem.

**Comment by lnikell** [comment]
@jasonbahl Thanks for the update. Looking forward to try new version, one it’s released.

**Comment by jasonbahl** [comment]
@lnikell @rburgst Hey! I'm preparing v0.5.0 for release (#250). 

It has better support for mapping Field Groups to specific Types in the Schema and an option for you to explicitly set which GraphQL Types the Field Group should show on. 

If you could test with that release, that would be sweet!

Thanks!

**Comment by rburgst** [comment]
@jasonbahl I rechecked with 0.5.0 and my problem persists, so my patch in https://github.com/AdvancedCustomFields/acf/pull/403 is still required

**Comment by jasonbahl** [comment]
@rburgst @lnikell would you agree that with @rburgst findings I can safely close this issue as it appears to be an ACF Core issue and not a "WPGraphQL for ACF" issue?

**Comment by lnikell** [comment]
@jacobarriola thanks Jason, it could be closed. All related issues tell that it's an issue on ACF/Gutenberg side.

**Comment by jasonbahl** [comment]
Closing this as there's been no response since May 2021

**Comment by jasonbahl** [comment]
I would also recommend checking out the new version of the plugin being built over here: https://github.com/wp-graphql/wpgraphql-acf.  It's the version that will be released to WordPress.org and then this repo will be archived.
